### ISSUE TITLE
The list is not being saved in local storage

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/ng-todo#14]
The list should be saving in local storage. This is not happening.

**Comment by ruslanguns** [comment]
I'll do it! 😉

**Comment by JasonFritsche** [comment]
@ruslanguns I've assigned this issue to you.

**Comment by ruslanguns** [comment]
Well, it was already implemented by #5 😂 from Oct 30, 2019. Well what other issue do you have?

**Comment by ruslanguns** [comment]
I see, it is not consistent, if you change the state of the item to isChecked it does not updates the state. I will fix it.
